[package]
name = "cake"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "cake"
path = "src/main.rs"

[dependencies]
cake-blacklist = { path = "../crates/cake-blacklist" }
cake-complete = { path = "../crates/cake-complete" }
cake-editor = { path = "../crates/cake-editor" }
cake-env = { path = "../crates/cake-env" }
cake-exec = { path = "../crates/cake-exec" }
cake-highlight = { path = "../crates/cake-highlight" }
cake-platform = { path = "../crates/cake-platform" }
cake-platform-unix = { path = "../crates/cake-platform-unix" }
cake-proc = { path = "../crates/cake-proc" }
cake-prompt = { path = "../crates/cake-prompt" }
cake-reader = { path = "../crates/cake-reader" }
cake-syntax = { path = "../crates/cake-syntax" }
